[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "getnovel"
description = "Tool based on Scrapy framework to Get novel on websites"
readme = "README.rst"
requires-python = ">=3.7"
keywords = ["crawler", "scrapy"]
license = { text = "MIT" }
version = "1.4.0"
classifiers = [
    "Framework :: Scrapy",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Operating System :: OS Independent"
]
dependencies = [
    "Scrapy >= 2.7.1",
    "Pillow >= 9.4.0",
    "tldextract >= 3.4.0",
    "importlib-metadata >= 4.2.0; python_version<'3.8'",
    "importlib-resources >= 5.10.2; python_version<'3.9'"
]

[project.optional-dependencies]
dev = [
    "black >= 22.12.0",
    "ipython >= 7.34.0",
    "flake8 >= 5.0.4"
]

[project.scripts]
getnovel = "getnovel:run_main"
